<?php
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2023 JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

use Jajuma\PotNote\Block\PowerToys\Note;
use Magento\Framework\Escaper;

/** @var Note $block */
/** @var Escaper $escaper */
$magewire = $block->getMagewire();
$note = $magewire->getNote();
?>
<div id="powertoys-note">
    <?php if ($magewire->getMessagePotNote()) : ?>
        <p class="message-note"><?= $magewire->getMessagePotNote() ?></p>
    <?php endif; ?>
    <textarea id="note-input" class="note-input" wire:model.defer="note" disabled></textarea>
    <br>
    <div class="note-action">
        <button id="noteEditBtn" onclick="editNote()">
            <svg xmlns="http://www.w3.org/2000/svg" height="19" width="19" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152V424c0 48.6 39.4 88 88 88H360c48.6 0 88-39.4 88-88V312c0-13.3-10.7-24-24-24s-24 10.7-24 24V424c0 22.1-17.9 40-40 40H88c-22.1 0-40-17.9-40-40V152c0-22.1 17.9-40 40-40H200c13.3 0 24-10.7 24-24s-10.7-24-24-24H88z"/></svg>
            <span><?= __('Edit') ?></span>
        </button>
        <button id="noteSaveBtn" wire:click="saveNote">
            <svg xmlns="http://www.w3.org/2000/svg" height="19" width="19" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M48 96V416c0 8.8 7.2 16 16 16H384c8.8 0 16-7.2 16-16V170.5c0-4.2-1.7-8.3-4.7-11.3l33.9-33.9c12 12 18.7 28.3 18.7 45.3V416c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V96C0 60.7 28.7 32 64 32H309.5c17 0 33.3 6.7 45.3 18.7l74.5 74.5-33.9 33.9L320.8 84.7c-.3-.3-.5-.5-.8-.8V184c0 13.3-10.7 24-24 24H104c-13.3 0-24-10.7-24-24V80H64c-8.8 0-16 7.2-16 16zm80-16v80H272V80H128zm32 240a64 64 0 1 1 128 0 64 64 0 1 1 -128 0z"/></svg>
            <span><?= __('Save') ?></span>
        </button>
    </div>
    <script type="text/javascript">
        editNote = () =>  {
            let notePopup = document.querySelector("#powertoys-note");
            let noteTextArea = notePopup.querySelector('#note-input');

            noteTextArea.disabled = false;
            noteTextArea.focus();

            notePopup.querySelector("#noteEditBtn").style.display = "none";
            notePopup.querySelector("#noteSaveBtn").style.display = "flex";

        }
    </script>
    <style>
        .powertoys-modal[data-action-id="pot_note"] {
            max-width: 450px;
            width: 80vw;
        }

        .powerToysModalWrapper .powertoys-modal.powertoys-modal-pot_note {
            max-height: 80vh;
            top: 50% !important;
            left: 50% !important;
            transform: translate(-50%, -50%) !important;
            overflow-y: auto;
            padding-bottom: 10px;
        }

        .powertoys-modal-pot_note .note-input {
            width: 100%;
            min-height: 200px;
            height: fit-content;
        }

        .jajumaLightMode ~ .powerToysModalWrapper .powertoys-modal-pot_note .note-input:disabled {
            background-color: rgba(255, 255, 255, .67);
            border: none;
        }

        .powertoys-modal-pot_note .note-input:disabled {
            background-color: rgba(239, 239, 239, 0.2);
            border: none;
        }

        .powertoys-modal-pot_note button:first-child {
            margin-right: 3px;
        }

        .powertoys-modal-pot_note .note-action {
            display: flex;
            margin-top: 6px;
            margin-bottom: 5px;
            gap: 6px;
            justify-content: end;
        }

        .powertoys-modal-pot_note .note-action #noteSaveBtn {
            display: none;
        }

        .powertoys-modal-pot_note .note-action button {
            display: flex;
            gap: 6px;
            align-items: center;
        }

        #powertoys-note .message-note {
            text-align: center;
            margin-bottom: 4px;
        }
    </style>
</div>
